### ISSUE TITLE
Support for plot title

### ISSUE THREAD

**Issue by xdk78** [data-forge-notebook/plot#40]

**Comment by ashleydavis** [comment]
This can be done. Please make sure you upgrade to Plot 1.0.21.

See example here:
https://github.com/data-forge-notebook/plot-examples/blob/master/typescript/example-1-with-title.ts

And here:
https://github.com/data-forge-notebook/plot-examples/blob/master/react/src/App.js

You can find the update docs for the new `title` field here:
https://data-forge-notebook.github.io/plot/docs/plot.iplotconfig
